"""
Django settings for active_annotator project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4dzpw5e-5ymy=f1(#eetg!u8g8&6+^$!^q9nv!m05!ti1-m=s4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3-rd party apps
    'bootstrap3',
    # custom tags
    'extratags',
    # custom apps
    'accounts',
    #'mt_annotate',
    #'mt_manage',
    'translation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'active_annotator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'active_annotator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
#LANGUAGE_CODE = 'ja-jp'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# auto transaction of "commit on success" for all view
ATOMIC_REQUESTS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_DIR = 'static'
MEDIA_DIR  = 'media'

BASE_URL = 'http://kanaf.info:8000'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, STATIC_DIR)
    #'/var/www/static/',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'STATIC_FILES')
else:
    #STATIC_ROOT = os.path.join(BASE_DIR, STATIC_DIR)
    MEDIA_ROOT  = os.path.join(BASE_DIR, MEDIA_DIR+'/')
    #MEDIA_ROOT  = os.path.join(BASE_DIR, MEDIA_DIR)
    #STATIC_URL  = os.path.join(BASE_URL, STATIC_DIR+'/')
    STATIC_URL  = '/%s/' % STATIC_DIR
    #MEDIA_URL   = os.path.join(BASE_URL, MEDIA_DIR+'/')
    MEDIA_URL   = '/%s/' % MEDIA_DIR

TRAVATAR_PATH = '/export/storage-ssd/src/travatar'
CKYLARK_PATH = '/export/storage-ssd/src/ckylark'

